spring:
  application:
    name: reactive-service

logging:
  level:
    io:
      codifica:
        test:
          simple:
            reactiveservice: INFO

feature:
  netty:
    ioWorker:
      count: 4
      custom:
        enable: false
